top_srcdir   = /home/roy/akasmsd/libsms
top_builddir = /home/roy/akasmsd/libsms
srcdir       = /home/roy/akasmsd/libsms/
builddir     = /home/roy/akasmsd/libsms/
VPATH        = /home/roy/akasmsd/libsms/
# $Id$

LTLIBRARY_NAME          = liblibsms.la
LTLIBRARY_SOURCES       = libsms.c
LTLIBRARY_SHARED_NAME   = libsms.la
LTLIBRARY_SHARED_LIBADD = $(LIBSMS_SHARED_LIBADD)

include $(top_srcdir)/build/dynlib.mk
